### ISSUE TITLE
Todo 업데이트 기능 refactoring

### ISSUE THREAD

**Issue by rjsej12** [WANTED-TEAM03/pre-onboarding-10th-1-3#30]
## 🐣 만들고자 하는 기능
Todo 업데이트 시 수정한 내용이 없어도 API 요청 되는 부분을 제거하고자 합니다.

## 🐣 해당 기능을 구현하기 위해 할 일
- [ ] Todo 수정 내용 확인 및 처음 값과 비교작업

## 🐣 예상기간
4월 28일 ~ 4월 28일

**Comment by sangminlee98** [comment]
추가적으로 수정버튼 클릭 후 수정모드에서 투두 내용을 수정하고 취소한다음 다시 수정모드로 들어갔을 때, 이전 수정했던 내역이 남아있습니다!
TodoItem/index.tsx에서 handleCancelEdit 함수에서 setIsEditing을 false로 하기 전에 
`editInput값을 원래 Todo의 값으로 수정해주는 작업`이 필요할 것 같아요!

```
const handleCancelEdit = () => {
    if (window.confirm('수정한 내용이 사라집니다. 계속하시겠습니까?')) {
      editInput.setValue(todo); // 이 부분을 추가해주세요!
      setIsEditing(false);
    }
  };

```
